[[constraint]]
  branch = "master"
  name = "github.com/chromedp/cdproto"

[[constraint]]
  branch = "master"
  name = "github.com/chromedp/chromedp"
#  version = "0.1.2"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"


[prune]
  go-tests = true
  unused-packages = true
